(defun kill-special-buffers ()
  "Kills all buffers that were generated by emacs (*Something*)"
  (interactive)
  (save-excursion
    (dolist(buffer (buffer-list))
      (set-buffer buffer)
      (if (string-match "\\*.*\\*" (buffer-name buffer))
	(kill-buffer buffer)))))

(defun check-syntax ()
  "Checks the syntax for the current language best way it knows how"
  (interactive)
  (cond
   ((eq major-mode 'c++-mode) (compile compile-command))
   ((eq major-mode 'python-mode)
    (python-check (concat "pychecker --stdlib " buffer-file-name)))
   (t (message "Don't know which checker to use."))))


(provide 'topher-functions)
